server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proyecto2
    username: postgres
    password: sasa
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: asdfafasfasdfasfasfdasdfasfasdffsdfasdfasdfasdfasdfasdfasdfasfdasdfasfdasdfasdfasfdasdfasdfasdfasdfasdfasdfasdfasdfasdfasd
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui/index.html